- hosts: all
  become: yes
  become_user: root
  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-latest-openjdk.x86_64
    - role: opencore.keystores